version: '3.8'

services:
  db:
    image: postgres:14
    container_name: my_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: my_backend
    volumes:
      - ./backend:/app  # For local dev changes to reflect inside the container
      - ./data:/app/data  # So the backend container can access your .xlsx files
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASS: mypass
      DB_HOST: db
      DB_PORT: 5432
      # Add other environment variables as needed (e.g. TRIMBLE_MAPS_API_KEY, etc.)

  frontend:
    build: ./frontend
    container_name: my_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
