# Generated by Django 5.1.7 on 2025-03-15 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadPosting',
            fields=[
                ('load_id', models.IntegerField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('posting_status', models.CharField(blank=True, max_length=50, null=True)),
                ('source_system', models.CharField(blank=True, max_length=50, null=True)),
                ('has_appointments', models.BooleanField(default=False)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('is_high_value', models.BooleanField(default=False)),
                ('is_temperature_controlled', models.BooleanField(default=False)),
                ('total_distance', models.FloatField(blank=True, null=True)),
                ('distance_uom', models.CharField(blank=True, max_length=10, null=True)),
                ('total_weight', models.FloatField(blank=True, null=True)),
                ('weight_uom', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_stops', models.IntegerField(blank=True, null=True)),
                ('transport_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('managed_equipment', models.BooleanField(blank=True, max_length=100, null=True)),
                ('load_number_alias', models.CharField(blank=True, max_length=100, null=True)),
                ('is_carb', models.BooleanField(default=False)),
                ('fpc', models.BooleanField(blank=True, max_length=50, null=True)),
                ('fpo', models.BooleanField(blank=True, max_length=50, null=True)),
                ('division', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('extended_network', models.BooleanField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoadStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(blank=True, max_length=50, null=True)),
                ('stop_sequence', models.IntegerField(blank=True, null=True)),
                ('stop_type', models.CharField(blank=True, max_length=1, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('appointment_from', models.DateTimeField(blank=True, null=True)),
                ('appointment_to', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=200, null=True)),
                ('appointment_state', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('load_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='backendapp.loadposting')),
            ],
        ),
    ]
