# Generated by Django 5.1.7 on 2025-03-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadposting',
            name='load_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
