# Generated by Django 5.1.7 on 2025-03-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_alter_loadposting_load_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadposting',
            name='extended_network',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadposting',
            name='fpc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadposting',
            name='fpo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loadposting',
            name='load_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='loadposting',
            name='managed_equipment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
