# Generated by Django 5.1.7 on 2025-03-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_alter_loadposting_extended_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadposting',
            name='load_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
