# Generated by Django 5.1.7 on 2025-03-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_alter_loadposting_load_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadposting',
            name='managed_equipment',
            field=models.BooleanField(blank=True, max_length=50, null=True),
        ),
    ]
