# Generated by Django 5.1.7 on 2025-04-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0006_appuser_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='min_loaded_rpm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='favorite',
            name='min_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'origin', 'destination', 'transport_mode', 'capacity_type', 'min_loaded_rpm', 'min_weight')},
        ),
    ]
